### ISSUE TITLE
RvtFader help

### ISSUE THREAD

**Issue by AlbanGorreja** [jeremytammik/RvtFader#1]
Hi Jeremy.

I was doing some research for my studies about wifi signal in a building and I found the RvtFader you've created. I'm not a programmer but I was wondering if I can use it for a building in Revit. Is it possible for you to advise me how to implement RvtFadere in Revit 2019?

Thank you in advance,

Alban

**Comment by jeremytammik** [comment]
Just grab the sources from this repo and recompile. If you have any basic questions about compiling and installing Revit add-ins, this is not the right place for them! Please refer to the Revit API getting started material instead: https://thebuildingcoder.typepad.com/blog/about-the-author.html#2
